.gitignore
LICENSE
README.md
stage/LibUsbDotNet/LibUsbDotNet.csproj
stage/LibUsbDotNet/LibUsbDotNet.nuget.targets
stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApi.cs
stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApiHelpers.cs
stage/LibUsbDotNet/MonoLibUsb/MonoUsbCapability.cs
stage/LibUsbDotNet/MonoLibUsb/MonoUsbVersion.cs

Separated the API DllImport method definitions from the other helper method for libusb. Also reordered them to match the original order in the C++ header, libusb.h.
Here is the complete list of the method signatures: https://docs.google.com/spreadsheets/d/1sNY7vqtrPs3n6b5w8joHh-KPzfnkQRmX5EacvzP9mic/edit?usp=sharing
Added 4 new methods and their structures to the method headers. They are not tested yet. Which testing framework would you guys prefer? NUnit or xUnit? xUnit needs .NET Framework 4.5 or Core, not sure about NUnit.
I also added the LGPLv3 license to the repo in a standardized way, plus added two badges to the main readme.md.

libusb interop header refactoring, method list update, badges

---

stage/LibUsbDotNet/MonoLibUsb/Profile/MonoUsbProfileList.cs

Addresses #19.
Resolves an issue where an `InvalidOperationException: Collection was modified; enumeration operation may not execute.` is thrown when USB devices are removed (and possibly added) as they're being enumerated on a Linux platform using `LinuxDeviceNotifier` (`DeviceListPolling`).
Currently I've got a test set up where I use a .NET Core application running on a Raspberry Pi to send messages to a microcontroller over USB to toggle a relay on and off. This runs in a continuous loop and while it's running, I try unplugging the USB cable between the RPi and the device. Specifically, I follow this procedure:
1. Build and publish .NET application on a Windows 7 64-bit machine (`dotnet publish -c Release -r linux-arm -p:SolutionDir=../.. -o usb_device_test`),
2. Copy the folder over …

Fix bug with enumerating devices

---

appveyor.yml
stage/LibUsb.Common/LibUsb.Common.csproj
stage/LibUsbDotNet/LibUsbDotNet.csproj

- Set the AppVeyor build number to 100 so we are OK with semver
- Publish both LibUsb.Common as well as LibUsbDotNet
- Automatically push to NuGet when master is updated
Fixes #14 #25

Fix NuGet packaging

---

stage/LibUsbDotNet/DeviceNotify/DeviceNotifyEventArgs.cs
stage/LibUsbDotNet/DeviceNotify/Linux/LinuxDeviceNotifyEventArgs.cs
stage/LibUsbDotNet/DeviceNotify/WindowsDeviceNotifyEventArgs.cs

Addresses #18.
I've uploaded a package containing these changes to my company's private feed and it seems to work for my use case, but you might want to test these changes yourself before merging this PR.
In my case, I'm able to replace this:
```cs
public class PartialDeviceNotifyEventArgs : DeviceNotifyEventArgs
{
public PartialDeviceNotifyEventArgs(EventType eventType, int vendorId, int productId)
{
var device = new InternalUsbDeviceNotifyInfo { IdVendor = vendorId, IdProduct = productId };
var baseType = typeof(PartialDeviceNotifyEventArgs);
const BindingFlags bindingFlags = BindingFlags.NonPublic | BindingFlags.Instance;
baseType.GetField("mDevice", bindingFlags).SetValue(this, device);
baseType.GetField("mEventType", bindingFlags).SetValue(this, eventType);
}
// ...
}
```
With this: …

Allow DeviceNotifyEventArgs to be subclassed in client code

---

stage/LibUsbDotNet/WinUsb/Internal/WinUsbAPI.cs

Added a check when getting overlapped results to see if the interface was closed before returning the overlapped results. This fixes issue that manifests itself in a System.ObjectDisposedException being thrown upon program completion.

Fix bug related to WinUsb_GetOverlappedResult() (#16)

---

azure-pipelines.yml

The build was referencing outdated builds (which have since been removed), bump to newer versions.

Bump libusb, libusbK builds

---

src/LibUsbDotNet.Tests/LibUsbDotNet.Tests.csproj

Remove leftover reference to LibUsbDotNet.LibUsb

---

src/LibUsbDotNet/LibUsb/UsbDevice.DeviceHandle.cs
src/LibUsbDotNet/LibUsb/UsbDevice.cs

- Share the same across `TryOpen` and `Open`, making sure the descriptor is reset when `Open` is called
- Make `Dispose` a no-op when `disposed == true`, making it re-entrant.

Fix TryOpen, Dispose

---

src/LibUsbDotNet/LibUsb/UsbDevice.cs

deviceHandle is owned by Open/Close, and should not be modified by Dipose()

Fix a NullReferenceException in Dispose().

---

src/LibUsbDotNet/LibUsb/IUsbDevice.cs
src/LibUsbDotNet/LibUsb/UsbDevice.DeviceHandle.cs
src/LibUsbDotNet/LibUsb/UsbEndpointBase.cs
src/LibUsbDotNet/LibUsb/UsbEndpointReader.cs
src/LibUsbDotNet/LibUsb/UsbEndpointWriter.cs

Depend on the interface instead of the implementation, to make the coupling looser.

UsbEndpoint*: Accept an IUsbDevice object

---

azure-pipelines.yml
src/LibUsbDotNet/LibUsbDotNet.csproj
src/refs/LibUsbDotNet.LibUsb.refs.csproj

- Use `DownloadPipelineArtifact@2` instead of `DownloadBuildArtifacts@0` to fix a build break
- Update to the latest version of NerdBank.GitVersioning to fix a build break

Fix Azure DevOps pipelines

---

stage/BenchmarkCon/BenchmarkCon.csproj

BenchmarkCon expects to read the help tesk from an embedded resource. Make sure BenchmarkHelp.txt is compiled into the assembly as an embedded resource.

BenchmarkCon: Fix help text

---

stage/LibUsbDotNet/Info/UsbInterfaceInfo.cs

USB protocols like DFU provide extra bytes in descriptor -- pass the needed
information forward so application can utilize the information.
Signed-off-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>

UsbInterfaceInfo: Add extra bytes for descriptor

---

.gitignore
src/LibUsbDotNet/LibUsb/NativeLibraryVersion.cs

Add static class to get the native libusb version. This is useful for ensuring the libusb version LibUsbDotNet resolved is the expected version. When I built libusb 1.0.26 on both Fedora and Ubuntu using the default ./configure options, LibUsbDotNet resolved the 1.0.25 version that came pre-installed with OS.
Also added JetBrains Rider options directory to gitignore, it's such a minor change I don't think it needs its own PR.

Native libusb version

---

stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApiHelpers.cs
stage/LibUsbDotNet/MonoLibUsb/MonoUsbDevice.cs

MonoUsbDevice.GetDescriptor should pass the langId parameter to MonoUsbApi.GetDescriptor in order to have the correct parameters for the Control Transfer.
Otherwise, the Control Transfer fails with LIBUSB_ERROR_PIPE  (control request not supported) for all Descriptors EXCEPT Device Descriptor, Configuration Descriptor and String Descriptor index 0.
This pull request fixes null string descriptors in the UsbDevice.Info when LibUsbDotNet  is used under Linux or under Windows with libusb-1.0 backend (ForceLibUsbWinBack set true) ... This was my use case; Tested under Windows with libusb-1.0.26 and under Linux (on a raspberry Pi4)
This pull request probably also fixes #164
Probably also related to #122 #146 #188

Add langId parameter to MonoUsbApi.GetDescriptor

---

.github/workflows/build.yaml
src/BenchmarkCon/BenchmarkCon.csproj
src/Examples/Read.Isochronous/Read.Isochronous.csproj
src/Examples/Read.Only/Read.Only.csproj
src/Examples/Read.Write.Async/Read.Write.Async.csproj
src/Examples/Read.Write/Read.Write.csproj
src/Examples/Show.Info/Show.Info.csproj
src/LibUsbDotNet.Tests/LibUsbDotNet.Tests.csproj
src/LibUsbDotNet/Generated/Context.cs
src/LibUsbDotNet/Generated/Device.cs
src/LibUsbDotNet/Generated/DeviceHandle.cs
src/LibUsbDotNet/Info/UsbBaseInfo.cs
src/LibUsbDotNet/LibUsb/NativeLibraryResolver.cs
src/LibUsbDotNet/LibUsbDotNet.csproj

Since PR #193 will need a minimum of .NET Framework 4.6 anyway, I think it makes sense to update the target frameworks to .NET Standard 2.0 + .NET 6 + .NET 7.
Also removed the SecurityPermission attributes, since they are [deprecated](https://learn.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=windowsdesktop-8.0).

Update target frameworks

---

src/Examples/Show.Info/ShowInfo.cs
src/LibUsbDotNet/Info/UsbConfigInfo.cs
src/LibUsbDotNet/Info/UsbDeviceInfo.cs
src/LibUsbDotNet/Info/UsbEndpointInfo.cs
src/LibUsbDotNet/Info/UsbInterfaceInfo.cs

Fixes issue #187. I made the ToString methods of the various device info classes more verbose, let me know if we would rather put these in extra methods for those classes. 
Also switched to using object initializers for the info classes, just a code style thing.
If I messed up the format or order of any of the properties, let me know.
Sample output:
```
Device: 0x0100
DeviceClass: 0
DeviceSubClass: 0x00
VendorId: 0x04B4
ProductId: 0x00F3
Manufacturer: Cypress
Product: WestBridge 
SerialNumber: 0000000004BE
USB: 0x0200
MaxPacketSize: 64
NumConfigurations: 1
Configuration: 
Attributes: 0x80
ConfigurationValue: 1
MaxPower: 100
Interface: 
InterfaceId: 0
AlternateId: 0
Class: VendorSpec
Protocol: 0x00
SubClass: 0x00
Device: 0x0602
DeviceClass: 9
DeviceSubClass: 0x00
VendorId: 0x1D6B …
```

Show info example fix

---

src/LibUsbDotNet.Generator/EnumVisitor.cs
src/LibUsbDotNet.Generator/FunctionVisitor.cs
src/LibUsbDotNet.Generator/Generator.cs
src/LibUsbDotNet.Generator/LibUsbDotNet.Generator.csproj
src/LibUsbDotNet.Generator/NameConversions.cs
src/LibUsbDotNet.Generator/StructVisitor.cs

To fix issue #201. The errors were mostly caused by out of date calls to the Core.Clang library. I tried to replace them with closest equivalents I could find.
Also, I changed the target framework to .NET Framework 4.7, since it seems Nustache only supports Framework. Other changes to the .csproj were to fix various warnings I got when building.
The project can build now, but I'm not sure if it will actually be useful at generating bindings. However, I'm not sure how much that matters, will it ever be necessary to re-generate bindings for libusb?

Allow LibUsbDotnet.Generator to build.

---

stage/LibUsbDotNet.sln

I have multiple versions of VS installed (2017, 2019, 2022) on my system. By default (double click) the solution opens with VS2017 which cannot build it. Hence the changes to the solution file to open with VS2022.
NOTE: Project type GUIDs were automatically updated by Visual Studio.
`FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` C#
`9A19103F-16F7-4668-BE54-9A1E7A4F7556` C# (forces use of [SDK project system](https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md#project-type-guids))

Updated solution file to open with VS2022.

---

.github/workflows/build.yaml
stage/LibUsbDotNet/LibUsbDotNet.csproj
stage/LibUsbDotNet/Main/UsbDeviceFinder.cs

It seems that the only issue is the removal of BinaryFormatter from Net 8.0 (was already deprecated).
In V2, the BinaryFormatter is only used for some Load/Save methods inside the UsbDeviceFinder class. 
While I do not use that particular class myself, so I haven't really tested it (even if I were to use it, Saving and Loading finder objects does not seem to be used all that much/all that useful), I did replace the existing Serializer with JsonSerializer and that should work just fine.
#236

NET 8.0 build for V2.0

---

.github/workflows/build.yaml
src/BenchmarkCon/BenchmarkCon.csproj
src/Examples/Hotplug/Hotplug.csproj
src/Examples/Read.Isochronous/Read.Isochronous.csproj
src/Examples/Read.Only/Read.Only.csproj
src/Examples/Read.Write.Async/Read.Write.Async.csproj
src/Examples/Read.Write/Read.Write.csproj
src/Examples/Show.Info/Show.Info.csproj
src/LibUsbDotNet.Tests/LibUsbDotNet.Tests.csproj
src/LibUsbDotNet/LibUsb/UsbException.cs
src/LibUsbDotNet/LibUsbDotNet.csproj

While I do not personally use this branch, the changes seem trivial enough: only a new obsolescence warning about some Exception API that can be treated by either simply removing the offending API, or marking it as obsolete in turn, as a heads-up for the end-users; choosing the latter here, as the nicer option ...  
#235

NET 8.0 build for V3.0

---

README.md

Updating download location for libusb-win32 to pass along the redirect given from the sourceforge download link. 
Sourceforge download content:
Sourceforge will only be used for mailing list since Feb 2024. Please go to https://github.com/mcuee/libusb-win32/releases to  download the latest official releases.

Updating download location for libusb-win32

---

stage/LibUsbDotNet/MonoLibUsb/MonoUsbDevice.cs

Hi,
I'm using LibUsbDotNet to talk to STM32 DfuSe devices. Using the default DFU implementation by ST, the whole communication is expected to be done using control transfers.
Due to hardware limitations, execution of some DFU commands on the embedded device might take longer than 1000ms. This results in a timeout error due to the timeout being hard coded in LibUsbDotNet.
This small change fixes my problem and has no impact on other users, because the default behavior is unchanged.
Please consider my PR as a suggestion. I think, it could be helpful for other users, too, but I explicitly don't require you to merge it.
Best regards,
Michael

Make control transfer timeout configurable in MonoUsbDevice
